apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bxqw5fgnt-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-944fc3583d.jde2.p3.openshiftapps.com/rhtap/rhtap-qe:267a220ffa0ec2fd48f719bb81ef6cc18c04a562@sha256:a977d39cf7761c6fbc53c6d29001f71d1e9e89c168785b3b4cbb6abe8ef10d8b
          name: container-image
